### ISSUE TITLE
Theme 'Sponsors' page

### ISSUE THREAD

**Issue by dipakmdhrm** [drupalpune/campsite#112]
## Theme 'Sponsors' page
- Page path '/sponsors'
  - View of nodes of Sponsor type.
- [Figma](https://www.figma.com/file/LbZhGpHQaQ16ofzQISHuMY/DCP-2023-Website?type=design&node-id=1788-31203&mode=design&t=NFoPZ49Ls15MWtwB-4)
- Design:

![sponsors](https://github.com/drupalpune/campsite/assets/4610167/a812afe5-09e3-4d9e-a81b-1ae6904c512c)

**Comment by Prashant114606** [comment]
PR for this https://github.com/drupalpune/campsite/pull/114

I have a couple of questions about this

1. How are we planning to add a description inside the page title block?
2. I have themed the view header, but the content is not provided, so I didn't export it.

**Comment by dipakmdhrm** [comment]
There are some visual anomalies we need to adress:
![sponsors-error](https://github.com/drupalpune/campsite/assets/4610167/56753b5a-c7d3-44fb-a559-f20f5b11915d)

@Prashant114606

**Comment by dipakmdhrm** [comment]
My bad. 
Deploy didn't clear cache. This looks much better.

![sponsors-error-fixed](https://github.com/drupalpune/campsite/assets/4610167/3dd0b655-e561-439e-a222-1063b81a9c3e)

**Comment by abhisekmazumdar** [comment]
This can be closed now: https://www.drupalpune.in/sponsors
