### ISSUE TITLE
Add Container around Landing page content

### ISSUE THREAD

**Issue by dipakmdhrm** [drupalpune/campsite#140]
## Context
Landing page content (when text is added in body field) doesn't have a container around it.

![Image](https://github.com/drupalpune/campsite/assets/4610167/da410ce0-a9cf-4937-b0ad-25f2823ec30e)

## To Do
Add Container around Landing page content

**Comment by siddharth7998** [comment]
@dipakmdhrm Do we have any spacing/margin defined around the content or is there any references for it?

**Comment by abhisekmazumdar** [comment]
Sharing a figma link with You over the slack.

**Comment by abhisekmazumdar** [comment]
Changes deployed & verified over test(pantheon).
