### ISSUE TITLE
Social blocks appear below one another instead of side-by-side

### ISSUE THREAD

**Issue by dipakmdhrm** [drupalpune/campsite#141]
## Context
Social blocks appear below one another instead of side-by-side:
![tweet-below-one-another](https://github.com/drupalpune/campsite/assets/4610167/d15e3d4e-91c3-4994-99a1-840a131103d0)

## To Do
Make Social blocks appear side-by-side.

## Technical info
Each block uses the following wrapper:

    <div class="twitter-block"></div>

**Comment by abhisekmazumdar** [comment]
Changes deployed & verified over test(pantheon).
