### ISSUE TITLE
Gin doesn't behave well with paragraphs

### ISSUE THREAD

**Issue by dipakmdhrm** [drupalpune/campsite#144]
Gin bug
![admin-theme](https://github.com/drupalpune/campsite/assets/4610167/4558b1bd-1d54-4f94-b6b9-c5a70b25cac9)

## To Do
Change admin theme to Claro

**Comment by abhisekmazumdar** [comment]
Ok that on me. I will make it happen.

**Comment by abhisekmazumdar** [comment]
Changes: https://github.com/drupalpune/campsite/commit/2ffcce39b8d89e79adebd7a494debe5f136f3d6e

**Comment by abhisekmazumdar** [comment]
TODO: Remove gin from composer.
