### ISSUE TITLE
Fix the "In collaboration with" block in the home >> footer page

### ISSUE THREAD

**Issue by abhisekmazumdar** [drupalpune/campsite#150]

**Comment by siddharth7998** [comment]
@abhisekmazumdar This has been done on dev environment, please review!
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/765beab8-f814-482a-a015-71ca7f0ca823">

**Comment by abhisekmazumdar** [comment]
Can we make the logo background white again?
Like on live site
<img width="457" alt="image" src="https://github.com/user-attachments/assets/04e4fd28-25ff-44e2-afde-c950dab93082">

Note: We have Tailwind CSS setup on the site. You can use its classes if needed.

Also lets make it open new tab?

**Comment by siddharth7998** [comment]
Sure, its update now!

<img width="1306" alt="image" src="https://github.com/user-attachments/assets/a457bef5-0117-43af-8228-073a93325b9d">

**Comment by abhisekmazumdar** [comment]
Yes perfect I'm updating it over live.

**Comment by abhisekmazumdar** [comment]
I have updated the live site with the new block HTML.

Thank you @siddharth7998 for taking care of this.
