### ISSUE TITLE
Bugs during session submission process for anonymous

### ISSUE THREAD

**Issue by dipakmdhrm** [drupalpune/campsite#151]
Bugs

Bug|Screenshot/Recording
-|-
Profile tabs are not themed|![profile-tabs](https://github.com/user-attachments/assets/25bb65d9-746c-469d-8839-cd49e6c68097)
Co-presenter field loader is repeated|https://github.com/user-attachments/assets/41dcf312-54d3-484b-ad76-2688267a1878
Speaker agreement link is not visible|https://github.com/user-attachments/assets/50a51129-5661-4eb3-a1eb-2daf2e2dd0f8
Status message looks like header, this could be more prominent. I missed this after registration|![message](https://github.com/user-attachments/assets/fdbce979-b12b-4d5b-832b-3757db5958a7)

**Comment by abhisekmazumdar** [comment]
All the bugs here are resolved other than just the status message looks.
