### ISSUE TITLE
The article and/or blog page should be themed with author bio block

### ISSUE THREAD

**Issue by shinde-rahul** [drupalpune/campsite#163]
As discussed in the call, we should have a place for all our write-ups, such as blogs and announcements.
The article content type is available; we need to theme it accordingly.

**Comment by abhisekmazumdar** [comment]
The Content type: Article need some theming: https://dev-campsite2024.pantheonsite.io/admin/content?title=&type=article&status=All

I have created some sample content for the Dev Pantheon website. Please review the content and apply the appropriate theme.
AC:

- Content type: Article node pages should be properly themed with proper spacing.
- If the node has an image, make it centered with proper spacing.
- Add author info and when published info back into the Twig. I see the config is enabled for the content type, but still the info is not being shown on the detailed page. I suspect Twig is the issue, which doesn't have those variables or templates in it.

**Comment by abhisekmazumdar** [comment]
FIXED: https://github.com/drupalpune/campsite/pull/177
