### ISSUE TITLE
Create a Accommodation landing page with Tailwind css html body

### ISSUE THREAD

**Issue by abhisekmazumdar** [drupalpune/campsite#166]
Create new Landing page node: https://www.drupalpune.in/node/add/landing_page

Add Full HTML body text style it with help of Tailwind css.

**Comment by abhisekmazumdar** [comment]
Example page: https://www.drupalpune.in/accommodations-option

I will copy this to live

**Comment by abhisekmazumdar** [comment]
We need to decide on a menu link place for this.

@nikitaaswani @dipakmdhrm @shriaas-qed any inputs on this?

**Comment by shinde-rahul** [comment]
The following will be the menu items,

- Home
- Venue
  - Yashada
  - Accommodation preferences
  - Networking Dinner
- Session
  - Schedule
  - Accepted
  - Tracks
- Workshops
- Sponsors
- DAP
  - DCP 2024 Team
  - About
- Register

**Comment by abhisekmazumdar** [comment]
I have updated the menu links with Venu for now. Rest will be updated as things goes live.

**Comment by abhisekmazumdar** [comment]
Its live: https://www.drupalpune.in/accommodations-suggestion
