### ISSUE TITLE
Lists need theming

### ISSUE THREAD

**Issue by ajitdev** [drupalpune/campsite#168]
The lists (`ul` and `ol`) are not themed.

Example page - https://www.drupalpune.in/session/enhancing-drupal-php-8-exploring-new-features-and-compatibility

Screenshot:
![image](https://github.com/user-attachments/assets/68c15739-d38c-49f9-ac69-9c65a2074cb4)

**Comment by abhisekmazumdar** [comment]
Thanks to @siddharth7998 this is not fixed. Changes will be deployed tonight.
